### ISSUE TITLE
Clicking on settings in the modsurfer application renders the screen empty

### ISSUE THREAD

**Issue by shivaylamba** [dylibso/modsurfer#30]
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/19529592/227468009-8f0447b0-a769-4ef8-8c76-8c0cb00dffbf.png">
when clicking on the settings icon on the lower right, nothing happens and the screen becomes empty

**Comment by nilslice** [comment]
Yes, this is a placeholder page for now - good find :) There will be some settings here to configure in a future version!
