### ISSUE TITLE
 Resource Limit check fail on size.max.

### ISSUE THREAD

**Issue by mtb0x1** [dylibso/modsurfer#71]
_**Command to reproduce :**_
```log
  cargo run generate -p /tmp/tfjs-backend-wasm.wasm -o /tmp/tfjs-backend-wasm.yaml
  cargo run validate -p /tmp/tfjs-backend-wasm.wasm -c /tmp/tfjs-backend-wasm.yaml
```
(* `tfjs-backend-wasm.wasm` can be found [here](https://www.npmjs.com/package/@tensorflow/tfjs-backend-wasm?activeTab=code))

_**Result :**_
```log
┌────────┬──────────┬──────────────┬───────────┬────────────────┬──────────┐
│ Status │ Property │ Expected     │ Actual    │ Classification │ Severity │
╞════════╪══════════╪══════════════╪═══════════╪════════════════╪══════════╡
│ FAIL   │ size.max │ <= 303.8 KiB │ 303.8 KiB │ Resource Limit │ |        │
└────────┴──────────┴──────────────┴───────────┴────────────────┴──────────┘
```
_**Expected Result :**_
Validation passes successfully. 

looks like a Serialization/Deserialization issue : 
Manual serialization in : https://github.com/dylibso/modsurfer/blob/0a915ee4978d16b1ed0c199320d10d382bf79200/validation/src/lib.rs#L954
Default Deserialization  in : https://github.com/dylibso/modsurfer/blob/0a915ee4978d16b1ed0c199320d10d382bf79200/validation/src/lib.rs#L877

**Comment by nilslice** [comment]
thanks for reporting this! I can push a quick fix to round up the size - I've also wondered if not adding this size.max to a generated checkfile would be a better idea?

**Comment by mtb0x1** [comment]
I think keeping the size validation would be nice, the size is an indicator of potential bloat in the module.
On the other hand, storing the 'human format' in the check file and testing against is not mandatory. I would say we need to display the human format only when displaying a result (fail).

so changing https://github.com/dylibso/modsurfer/blob/0a915ee4978d16b1ed0c199320d10d382bf79200/validation/src/lib.rs#L954 to
```rust 
size.max = Some(module.size.to_string()); 
``` 
potentially solve and simplify the whole process ?

**Comment by nilslice** [comment]
It is tempting, but I think having the human readable size in this representation is helpful for at-a-glance reviews as well as making edits to the value. 

My thinking here is before encoding the generated checkfile, we add maybe 10% of the detected size to give it a bit of padding/tolerance. Perhaps 10% is too high though. What do you think?

**Comment by mtb0x1** [comment]
Sounds good to me, we will be dealing with wasm binary files after all 10% should do it.
